% Parameters in S-S form
function [Lam,Sigma,mu,G,Omega] = makePara(theta, Sn) 

tau = Sn.tau;
lambda = Sn.lambda;

% M.E.
ntau = rows(Sn.tau);

%    [ Lambda    0   ;...
%           0             I   ];
% Merge the Lambda and Restriction
lam = ones(ntau, 3);
lam(:,2) = (ones(ntau,1)-exp(-tau*lambda))./(tau*lambda);
lam(:,3) = ((ones(ntau,1)-exp(-tau*lambda))./(tau*lambda)) - exp(-tau*lambda);
Lam = [lam, zeros(10,2); zeros(2,3), diag(ones(2,1))];
Sigma = diag(theta(Sn.indSig));

% T.E.
mu = theta(Sn.indMu); 
Gm = theta(Sn.indG);
G =  [Gm(1)   Gm(2)   Gm(3)    Gm(4)    Gm(5) ;...
              0         Gm(6)   Gm(7)    Gm(8)    Gm(9) ;...
              0              0        Gm(10) Gm(11) Gm(12)  ;...
              0              0            0          Gm(13)     0  ;...
              0              0            0             0          Gm(14)  ];

%G =  [Gm(1)   Gm(2)   Gm(3)    Gm(4)    Gm(5) ;...
%          Gm(6)   Gm(7)   Gm(8)    Gm(9)    Gm(10) ;...
 %         Gm(11) Gm(12) Gm(13) Gm(14) Gm(15)  ;...
  %            0              0            0         Gm(16)     0  ;...
    %          0              0            0             0          Gm(17)  ];

Ome = theta(Sn.indOmega);
Omega = [Ome(1) Ome(2) Ome(3) Ome(4) Ome(5) ;...
                    Ome(2) Ome(6) Ome(7) Ome(8) Ome(9) ;...
                    Ome(3) Ome(7) Ome(10) Ome(11) Ome(12) ;...
                    Ome(4) Ome(8) Ome(11) Ome(13) Ome(14) ;...
                    Ome(5) Ome(9) Ome(12) Ome(14) Ome(15) ];
end